name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Update libs and build
        run: cd frontend && npm ci && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
